kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |-
     {
        "Serilog1": {
          "MinimumLevel": {
            "Default": "Debug",
            "Override": {
              "Microsoft.AspNetCore": "Debug"
            }
          },  
          "WriteTo": [
            {
              "Name": "File",
              "Args": {
                "path": "Logs/log.txt",
                "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] ({SourceContext}) {Message:lj}{NewLine}{Exception}",
                "rollingInterval": "Day",
                "maxFileSize": "10MB",
                "maxHistory": 30
              }
            }
          ]
        },
      
        "Serilog": {
          "MinimumLevel": {
            "Default": "Debug",
            "Override": {
              "Microsoft.AspNetCore": "Debug"
            }
          },
          "ElasticConfiguration": {
            "Uri": "http://10.0.0.61:9200"
          },
      
          "WriteTo": [
            {
              "Name": "File",
              "Args": {
                "path": "Logs/log.txt",
                "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] ({SourceContext}) {Message:lj}{NewLine}{Exception}",
                "rollingInterval": "Day",
                "maxFileSize": "10MB",
                "maxHistory": 30
              }
            },
            {
              "Name": "Elasticsearch",
              "Args": {
                "nodeUris": "http://10.0.0.61:9200",
                "indexFormat": "Specta-API-{0:yyyy.MM.dd}",
                "autoRegisterTemplate": true,
                "autoRegisterTemplateVersion": "ESv7",
                "failureCallback": "Failed to write log event to Elasticsearch",
                "emitEventFailure": "WriteToSelfLog",
                "numberOfShards": 2,
                "numberOfReplicas": 1
              }
            }
          ]
        },
      
      
      
        "AllowedHosts": "*",
        "LoggerSettings": {
          "AppName": "SpectaApps",
          "ElasticSearchUrl": "",
          "WriteToFile": true,
          "MinimumLogLevel": "Information",
          "LogPath": "Logs/logs.json",
          "StructuredConsoleLogging": true
        },
        "MiddlewareSettings": {
          "EnableHttpsLogging": true
        },
        "CorsSettings": {
          "AllowedOrigins": [
            "https://www.sterling.ng",
            "https://www.sterling.ng",
            "https://www.sterling.ng"
          ]
        },
      
        "Jwt": {
          "SecretKey": "7d2a6211-1a43-4bb5-8c87-39b9d6ea4835",
          "Issuer": "https://specta-api.sterling.ng",
          "Audience": "https://specta-api.sterling.ng"
        },
        "AppSettings": {
          "isLive": true,
          "UseDummyScore": false,
          "BookLoanFromCoreBanking": true,
          "EncryptionKey": "EncryptionKey",
          "EncryptResponseDataBufferSize": 1048576,
          "EncryptResponseData": true,
          "AddBufferSize": false,
          "UseEncryptedData": true,
          "OtpValidityTime": 5, 
          "JwtValidityTime": 15, 
          "StampDutyRate": 0.125,
          "Channel": "SPECTAMOB",
          "Currency": "NGN",
          "RefreshTokenExpirationInDays": 7,
          "ExemptReceiveWebhook": "/api/v1/Webhook/Okhi",
          "ExemptOkhi": "/api/v1/Webhook/ReceiveWebhook",
          "ExemptDeepLink": "/.well-known/assetlinks.json",  
          "StoreUser": "specta.store@sterling.ng",
          "FrontEndBaseUrl": "https://specta.sterling.ng",
          "HypervergeUrl": "https://auth.hyperverge.co/login",
      
      
      
          "LoanChannels": [ "SpectaMobile", "Specta Web" ],
          "SeaBaas": {
            "BaseUrl": "http://eacbs-api-prod.apps.non-core-prod.sterlingbank.com/banks.asmx"
          },
          "LoanApi": {
            "BaseUrl": "http://172.18.1.22:8089"
          },
          "EmailService": {
            "BaseUrl": "http://10.0.0.66:9094/EmailService/SendMailWithAttachment"
          },
          "FundsLock": {
            "BaseUrl": "http://fiorano-api.apps.non-core-prod.sterlingbank.com/",
            "LockEndpoint": "restgateway/services/EacbsUpdate1/LockAmount",
            "UnlockEndpoint": "restgateway/services/EacbsUpdate1/UnlockAmount",
            "Hours": 720
          },
      
          "FeesAccount": {
            "Vat": "NGN2228501276",
            "Management": "NGN4424100005"
          },
          "LoanManagementBaseUrl": "http://loanmanagement-smartadapter.apps.core-prod.sterlingbank.com",
          "CurencyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      
          "Lendsqr": {
            "BaseUrl": "https://adjutor.lendsqr.com/v2/",
            "Token": "sk_live_n83OSw1k7jVYolWkArRag9c8DWuz4cg1Lm1vFusW",
            "CreateMandate": "direct-debit/mandates",
            "DebitMandate": "direct-debit/mandates/debit",
            "GetAllBanks": "direct-debit/banks?limit=100&page=1&sort_dir=ASC",
            "VerifyBankAcctNumber": "direct-debit/banks/account-lookup",
            "Frequency": "monthly",
            "DebitType": "all"
          },
          "Remita": {
            "BaseUrl": "https://api-core-platform-test.systemspecsng.com/services/remita-api-gateway/api/v1/mandate",
            "SetupMandate": "/setup",
            "MandateOtpRequest": "/activation/otp/request",
            "MandateOtpValidation": "/activation/otp/validation",
            "MandateStatus": "/status",
            "StopMandate": "/stop",
            "SendDebit": "/debit/send",
            "DebitStatus": "/debit/status",
            "DebitHistory": "/payment/history",
            "CancelDebit": "/debit/cancel"
          },
      
          "ApiGatewayCredential": {
            "BaseUrl": "https://api.sterling.ng/gateway/sandbox/api",
            "Email": "samuel.akabuike@sterling.ng",
            "Password": "UHJlc2NvdGNydXp5OQ=="
          },
          "AccountOpeningCredential": {
            "BaseUrl": "http://camsv3-api.apps.non-core-prod.sterlingbank.com/api",
            "NewAccountOpeningUrl": "https://accountopening-api-simulation.apps.non-core-prod.sterlingbank.com",
            "AccountPrefix": "232",
            "BranchCode": "002",
            "SectorT24Code": "4200",
            "CurrencyCode": "NGN",
            "IndustryT24Code": "4202",
            "Dao": "999",
            "AppId": "46",
            "ChannelId": "Specta",
            "IsRestricted": false,
            "AccountType": "Liability",
            "AccountCategory": "0",
            "Target": "1",
            "CustomerStatus": "1",
            "EncryptionKey": "b14ca5898a4e4142aace2ea2143a2410",
            "EncrytptionIv": "BE/s3V0HtpPsE+1x",
            "SecretKey": "ejzcwp0C61mOtuxU",
            "Iv": "smymmlpK2M/NkUub"
          },
      
          "DocumentType": [
            "NIN",
            "International Passport",
            "Drivers License",
            "Voters Card"
          ],
      
          "LoanType": [
            "Specta Xtreme",
            "Specta Basic",
            "Specta For Business"
      
          ],
          "CreditSearchBaseUrl": "https://spectamicroservices.az-engr-conv-ase.p.azurewebsites.net/api/creditbureausearch",
          "T24Service": {
            "EwBaseUrl": "http://10.0.0.230/ewService/service.asmx",
            "AccountManagementBaseUrl": "http://accountmanagement-api.apps.non-core-prod.sterlingbank.com/AccountManagement",
            "MailFrom": "specta@sterling.ng",
            "MailTo": "LoanProductOperations@sterling.ng,spectaproductmanagers@sterling.ng",
            "BanksUrl": "http://eacbs-api-prod.apps.non-core-prod.sterlingbank.com/banks.asmx",
            "BvnValidationUrl": "http://10.0.0.230/BVNValidation"
          },
      
          "SeedFiScore": {
            "BaseUrl": "https://stg-creditscoring.theseedfi.com/creditscoring/api/v1",
            "ScoreEndpoint": "baseline/calculate-credit-score/",
            "ApiKey": "zDu8oCGR.SD670OMZJzOjVRj42IAocjvtPNzDyxSb"
          },
          "MyBankStatement": {
            "BaseUrl": "https://mybankstatement.net/TP/api",
            "ClientId": "1",
            "ClientSecret": "ansds21*$SPP",
            "Username": "spectastatement@sterling.ng"
          },
          "GlobalLimit": {
            "Url": "http://globallimit-pilot.apps.non-core-prod.sterlingbank.com/api/v1/service",
            "Token": "67890FGHIJ34*&",
            "GlobalLimitRetryCount": 3,
            "GlobalLimitProductName": "SHORT.TERM1",
            "GlobalLimitAmount": 2000000,
            "BettingPercentageLimit": 5
          },
          "T24DbConnectionString": "Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.0.42.154)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SID=STERDB)));User Id=stafj;Password=Ster#123;",
          "LoanBookingDetails": {
            "Username": "FIORANOUSER",
            "Password": "123456",
            "Branch": "NG0020001",
            "ProductRate": 14,
            "RateType": "FIXED",
            "CloseTimeout": 5,
            "EndpointAddress": "http://10.0.42.155:8185/TAFJServices/services/OFSService",
            "MaxBufferPoolSize": 200000,
            "MaxReceievedMessageSize": 900000,
            "OpenTimeout": 5,
            "ReceiveTimeout": 5,
            "SendTimeout": 5,
            "LoanApiV2Url": "http://172.18.1.22:8089"
          },
          "CardTokenization": {
            "MinimumCharge": 50,
            "PaystackBaseUrl": "https://api.paystack.co/",
            "PaystackSecretKey": "sk_live_e1ac0a74c4d5c0e9f113e54cb1e99495c17e5907",
            "PaystackPublicKey": "pk_live_59483b77e732ea1f5f1b3b4e00cedf9a87293147",
            "SuspenseAccount": "0092933539"
          },
          "CurrentAccountLedgerCode": "CUR",
          "InsuranceAccount": "NGN2231000040001",
          "TransferType": 2,
          "NewIntraBankUrl": "http://intrabank-api-seabass.apps.non-core-prod.sterlingbank.com/api/v1/Intrabank",
          "NewIntrabankApplicationId": 58,
          "NewIntraBankKey": "C*F-JaNdRgUkXp2s",
          "NewIntraBankIV": "9z$C&F)J@NcRfUjX",
          "NewIntraBankHeader": "01AB5DD0DF414952A331BC3D329C9B4C",
          "FioranoFetchLoans": "http://fiorano-api.apps.non-core-prod.sterlingbank.com/restgateway/services",
          "FioranoFetchLoansEndpoint": "/LoanApi9/SbnReadLoanOrAccount/",
          "SkipGetBankingDate": true,
          "SpectaXtremeConfig": {
            "InterestRate": 40,
            "RepaymentDay": 28,
            "ManagementFeeRate": 1, 
            "Vat": 7.5, 
            "InsuranceFeeRate": 3.5, 
            "CommitmentFeeRate": 0,
            "ProductGroup": "7d34daa4-132d-4901-bf12-00f3fbb7f93c"
          },
      
          "DefaultBranchCode": "NG0020001",
          "SpectaBasicConfig": {
            "InterestRate": 38,
            "RepaymentDay": 28,
            "ManagementFeeRate": 1, 
            "Vat": 7.5, 
            "InsuranceFeeRate": 2.5, 
            "CommitmentFeeRate": 0,
            "ProductGroup": "091f0f48-abd6-42f0-ab8f-e6a3fec368df" 
          },
          "Cams": {
            "CamsServiceUrl": "http://camsv2-api.apps.non-core-prod.sterlingbank.com/api/v2/users",
            "SecretKey": "zAL7X5AVRm8l4Ifs",
            "IV": "BE/s3V0HtpPsE+1x"
          }
        },
      
        "ConnectionStrings": {
          "AppDbDev": "Server=10.0.41.101; Database=SpectaAppsDb; User=sa; Password=tylent; MultipleActiveResultSets=true; persist security info=true; TrustServerCertificate=True;",
          "AppDbProd": "Server=az-condb-serv.database.windows.net; Database=SpectaAppsDbPilot; User=SpectaApp_user; Password=$terl1ng123$; MultipleActiveResultSets=true; persist security info=true; TrustServerCertificate=True;"
        }
      }